name: deploy to Main environment

on:
  push:
    branches: [main]

jobs:
 linting:
    runs-on: ["self-hosted", "prod", "org-wide-runner"]
    container:
      image: python:3.7
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: setup environment
        shell: bash
        run: |
          /usr/local/bin/python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: lint
        shell: bash
        run: flake8 sourcecode
  unit-testing:
    runs-on: ["self-hosted", "prod", "org-wide-runner"]
    needs: linting
    container:
      image: python:3.7
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: setup environment
        shell: bash
        run: |
          /usr/local/bin/python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run unit tests
        shell: bash
        run: pytest -s tests --ignore tests/cli/test_cli.py 