name: deploy to Main environment

on:
  push:
    branches: [main]
  pull_request:
    branches: [ "main" ]

jobs:
  linting:
    runs-on: ["ubuntu-latest"]
    container:
      image: python:3.7
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: setup environment
        shell: bash
        run: |
          /usr/local/bin/python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install pylint pytest
          
      - name: lint
        shell: bash
        run: flake8 sourcecode
  unit-testing:
    runs-on: ["ubuntu-latest"]
    needs: linting
    container:
      image: python:3.7
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: setup environment
        shell: bash
        run: |
          /usr/local/bin/python -m pip install --upgrade pip
          python -m pip install -e .
          pylint life_expectancy.cleaning
      - name: run unit tests
        shell: bash
        run: pytest -s tests --ignore tests/cli/test_cli.py 