name: deploy to DEv environment

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  linting:
    runs-on: ["ubuntu-latest"]
    container:
      image: python:3.8
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: setup environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint pytest
      - name: lint
        continue-on-error: true
        run: |
          pylint life_expectancy.cleaning
  unit-testing:
    runs-on: ["ubuntu-latest"]
    needs: linting
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: setup environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint pytest
          pip install .
      - name: run unit tests
        run: pytest